version: '3'

services:
  pdf-ai-mapper:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./uploads:/app/uploads
      - ./processed_data:/app/processed_data
    environment:
      - PYTHONUNBUFFERED=1 