[project]
name = "pdf-ai-mapper"
version = "0.1.0"
description = "PDF and Image AI Mapper with OCR and automatic categorization"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.13.7,<3.14"
fastapi = ">=0.116.1,<0.117"
uvicorn = ">=0.35.0,<0.36"
python-multipart = ">=0.0.20,<0.0.21"
pytesseract = ">=0.3.13,<0.4"
pdf2image = ">=1.17.0,<2"
pypdf = ">=6.0.0,<7"
Pillow = ">=11.3.0,<12"
scikit-learn = ">=1.7.2,<2"
nltk = ">=3.9.1,<4"
numpy = ">=2.3.3,<3"
pydantic = ">=2.11.9,<3"
python-dotenv = ">=1.1.1,<2"
pytest = ">=8.4.2,<9"
pytest-cov = ">=7.0.0,<8"
pytest-mock = ">=3.15.0,<4"
pytest-asyncio = ">=1.2.0,<2"
requests = ">=2.32.5,<3"
aiohttp = ">=3.12.15,<4"
aiofiles = ">=24.1.0,<25"
pydantic-settings = ">=2.10.1,<3"
black = ">=24.0.0,<25"
flake8 = ">=7.0.0,<8"
mypy = ">=1.8.0,<2"
isort = ">=5.13.0,<6"

[tasks]
start = "python -m app.main"
test = "pytest tests/ -v"
test-unit = "pytest tests/unit/ -v"
test-integration = "pytest tests/integration/ -v"
test-e2e = "pytest tests/e2e/ -v"
test-cov = "pytest tests/ --cov=app --cov-report=html --cov-report=term-missing"
test-fast = "pytest tests/unit/ -v --tb=short"
test-all = "pytest tests/ -v --tb=short --cov=app --cov-report=term-missing"
lint = "flake8 app/ tests/ --max-line-length=100 --ignore=E203,W503"
format = "black app/ tests/ --line-length=100"
format-check = "black app/ tests/ --line-length=100 --check"
type-check = "mypy app/ --ignore-missing-imports"
