[project]
name = "pdf-ai-mapper"
version = "0.1.0"
description = "PDF and Image AI Mapper with OCR and automatic categorization"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.8"
fastapi = "==0.104.1"
uvicorn = "==0.23.2"
python-multipart = "==0.0.6"
pytesseract = "==0.3.10"
pdf2image = "==1.16.3"
PyPDF2 = "==3.0.1"
Pillow = "==10.1.0"
scikit-learn = "1.*"
nltk = "==3.8.1"
numpy = "2.*"
pydantic = "==2.4.2"
python-dotenv = "==1.0.0"

[tasks]
start = "python main.py"
